#!/usr/bin/env bash
# Installs and configures Nginx

sudo apt-get update -y
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx restart
