#!/usr/bin/env bash
# Script to update packages, installs and configures haproxy

sudo apt-get -y update
sudo apt-get -y install haproxy

cfg="frontend http
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 157505-web-01 54.157.148.124:80 check
        server 157505-web-02 100.25.111.105:80 check"
echo -e "$cfg" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
