#!/usr/bin/env bash
# Bash script that generates a MySQL dump
# and creates a compressed archiveout of it.
mysqldump -u root -p"$" --all-databases > backup.sql
tar -vczf "$(date +%d-%m-%Y)".tar.gz backup.sql
