#!/usr/bin/env bash
# This script displays the following contents in the file /etc/passwd:
#	username
#	user id
#	Home directory path for the user

while read -r line; do
	echo "$line" | cut -d ":" -f 1,3,6
done < /etc/passwd
