#!/usr/bin/env bash
# This script displays "Best School" 10 times, and includes "Hi" at the 9th time
count=1
while [ $count -lt 11 ]
do
	echo "Best School"
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	((count++))
done
