#!/usr/bin/env bash
# This script configures an Ubuntu Server to:
#	resolves localhost to 127.0.0.2
#	resolves facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.new
echo  "8.8.8.8  facebook.com" >>  ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
