#!/usr/bin/env bash
# This script fixes the container so that Nginx is running as the nginx user
# nginx must be listening on all active IPs on port 8080

sudo pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service ngin start
